on:
  release:
    types: [created]

name: Upload release assets after release is created
jobs:
  build:
    name: build binaries
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build
        run: |
          GOOS=windows  GOARCH=amd64  CGO_ENABLED=0 go build -o bin/windows/amd64/go-amqp-sniffer
          GOOS=linux    GOARCH=amd64  CGO_ENABLED=0 go build -o bin/linux/amd64/go-amqp-sniffer
          GOOS=linux    GOARCH=arm    CGO_ENABLED=0 go build -o bin/linux/arm/go-amqp-sniffer
          GOOS=darwin   GOARCH=amd64  CGO_ENABLED=0 go build -o bin/darwin/amd64/go-amqp-sniffer
          GOOS=darwin   GOARCH=arm64  CGO_ENABLED=0 go build -o bin/darwin/arm64/go-amqp-sniffer
      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: binaries
          path: bin/

  upload:
    name: Upload release assets
    runs-on: ubuntu-latest
    needs: [build]
    steps:

      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - uses: actions/checkout@v1

      - name: Download build artefacts
        uses: actions/download-artifact@v1
        with:
          name: binaries
          path: bin/

      - name: Create asset zips
        env:
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
        run: |
          mkdir assets
          zip assets/go-amqp-sniffer-${SOURCE_TAG}-windows-amd64.zip windows/amd64/go-amqp-sniffer README.md
          zip assets/go-amqp-sniffer-${SOURCE_TAG}-linux-amd64.zip linux/amd64/go-amqp-sniffer README.md
          zip assets/go-amqp-sniffer-${SOURCE_TAG}-linux-arm.zip linux/arm/go-amqp-sniffer README.md
          zip assets/go-amqp-sniffer-${SOURCE_TAG}-darwin-amd64.zip darwin/amd64/go-amqp-sniffer README.md
          zip assets/go-amqp-sniffer-${SOURCE_TAG}-darwin-arm64.zip darwin/arm64/go-amqp-sniffer README.md
          sha256sum assets/*zip > assets/SHASUMS256.txt
      - name: Upload release assets
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: './assets/*'